### ISSUE TITLE
Character Name Issue

### ISSUE THREAD

**Issue by Jhaun81** [ekrividus/autoAssist#1]
Hello! Love this addon but I have an issue with it not working with my characters that have similar names. Like if I have my characters named Kraunikik or Krauniki assist Kraunik it does not work. I think this is due to the name being the same in the first section.

**Comment by ekrividus** [comment]
Can you copy/paste your settings.xml for me.
I don't think that similarly named characters should be causing any issues. It uses, and compares with when you use the //aa assist <player> command, actual in game names. 
To my knowledge it hasn't for anyone before failed to get the right name. So I'd like to see if there's some other reason it might be misbehaving.
If you can also share the exact set of commands that leads to the issue, which characters you issue the commands and the like also helps a great deal.
